### ISSUE TITLE
Error in pseudorandom font selection

### ISSUE THREAD

**Issue by Jordy-VL** [FactoDeepLearning/DAN#4]
`~/code/DAN/OCR/line_OCR/ctc$ py main_syn_line.py `

```
Traceback (most recent call last):
  File "main_syn_line.py", line 181, in <module>
    main()
  File "main_syn_line.py", line 177, in main
    train_and_test(0, params)
  File "main_syn_line.py", line 65, in train_and_test
    model.generate_syn_line_dataset("READ_2016_syn_line")  # ["RIMES_syn_line", "READ_2016_syn_line"]
  File "/home/jordy/code/review/DAN/OCR/ocr_manager.py", line 89, in generate_syn_line_dataset
    img = dataset.generate_typed_text_line_image(sample["label"])
  File "/home/jordy/code/review/DAN/OCR/ocr_dataset_manager.py", line 859, in generate_typed_text_line_image
    return generate_typed_text_line_image(text, self.params["config"]["synthetic_data"]["config"])
  File "/home/jordy/code/review/DAN/OCR/ocr_dataset_manager.py", line 985, in generate_typed_text_line_image
    font_path = config["valid_fonts"][randint(0, len(config["valid_fonts"]))]
  File "/home/jordy/code/review/DAN/basic/utils.py", line 46, in randint
    return int(torch.randint(low, high, (1, )))
RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0
```

**Comment by FactoDeepLearning** [comment]
I assume this is because you have no valid font available in the "Fonts" directory

**Comment by chrisgwe** [comment]
I have the same error, could you tell me how to deal with this problem thank you!
<img width="1640" alt="image" src="https://github.com/FactoDeepLearning/DAN/assets/123208317/f7cbcf21-5925-4464-9050-967d46f3f639">
<img width="557" alt="image" src="https://github.com/FactoDeepLearning/DAN/assets/123208317/96772bd0-19d7-49bd-a2d4-840f29d4cd93">
